/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NangiRouteImport } from './routes/nangi'
import { Route as CasesAiPlaybookRouteImport } from './routes/cases.ai-playbook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NangiRoute = NangiRouteImport.update({
  id: '/nangi',
  path: '/nangi',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesAiPlaybookRoute = CasesAiPlaybookRouteImport.update({
  id: '/cases/ai-playbook',
  path: '/cases/ai-playbook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nangi': typeof NangiRoute
  '/cases/ai-playbook': typeof CasesAiPlaybookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nangi': typeof NangiRoute
  '/cases/ai-playbook': typeof CasesAiPlaybookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nangi': typeof NangiRoute
  '/cases/ai-playbook': typeof CasesAiPlaybookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nangi' | '/cases/ai-playbook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nangi' | '/cases/ai-playbook'
  id: '__root__' | '/' | '/nangi' | '/cases/ai-playbook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NangiRoute: typeof NangiRoute
  CasesAiPlaybookRoute: typeof CasesAiPlaybookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nangi': {
      id: '/nangi'
      path: '/nangi'
      fullPath: '/nangi'
      preLoaderRoute: typeof NangiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/ai-playbook': {
      id: '/cases/ai-playbook'
      path: '/cases/ai-playbook'
      fullPath: '/cases/ai-playbook'
      preLoaderRoute: typeof CasesAiPlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NangiRoute: NangiRoute,
  CasesAiPlaybookRoute: CasesAiPlaybookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
